api:
  user-service: lb://user-service/api/v1/users
server:
  port: 8082
spring:
  application:
    name: auth-service
  profiles:
    active: dev
jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-for-jwt-token-generation-keep-it-secure}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000} # 15 минут в миллисекундах
springdoc:
  api-docs:
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: health,metrics